services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  F7\Preview\:
    resource: '../Classes/*'

  F7\Preview\Backend\EventListener\PreviewEventListener:
    tags:
      - name: event.listener
        identifier: 'preview/backend/modify-page-module-content'

